apiVersion: v1
entries:
  anvil:
  - apiVersion: v2
    appVersion: 2.0.0
    created: "2021-05-05T14:36:02.716385+01:00"
    description: Opsforge ANViL helm packaged
    digest: 9ce8fac955f7110e65f11a6be950ab0f896fec8fa993002a39185001562567cf
    name: anvil
    type: application
    urls:
    - anvil-0.1.0.tgz
    version: 0.1.0
generated: "2021-05-05T14:36:02.713932+01:00"
