storagepath: CHANGE_ME

nginx:
  image:
    name: nginx
    tag: latest
  max_mem: 60Mi
  max_cpu: 60m

anvil:
  replicas: 1
  image:
    name: opsforge/anvil
    tag: latest
  host: anvil
  nodeport: 8001
  port: 80
  max_mem: 256Mi
  max_cpu: 500m
  storage:
    requests: 15Gi
  user:
    shell: zsh
    name: 'My.Name'
    email: 'email@address.com'
    repolist: 'abc'
    giturl: 'xyz'

cloud9:
  replicas: 1
  image:
    name: sapk/cloud9
    tag: latest
  host: cloud9
  nodeport: 8002
  port: 80
  max_mem: 256Mi
  max_cpu: 500m

sa:
  anvil: sa-anvil

secrets:
  basicauth: 'username:$apr1$3X/xufbq$xBqXarJxuOD0AMXJ4OYin.'
